"""The packed k-quant GEMM, on a real `q4_k_m` checkpoint.

`test_op_conformance.py` checks the packed kernels against
`backends/reference`, on inputs this suite authors. That comparison is exact in
its arithmetic and therefore *blind in one direction*: the reference decodes the
blocks with `python/pocketllm/quant/k_quants.py`, and the C kernels decode them
with `src/quant/blocks.h`. If the two read the bit layout the same wrong way --
the same nibble, from the same byte, shifted by the same amount -- the op-level
test passes on every shape while both are wrong together.

So there has to be a second authority that shares no code with either, and for
this model there is exactly one: llama.cpp, which wrote the format and quantized
this checkpoint. A file quantized by llama.cpp and read back by llama.cpp is the
only thing in this tree that can say "the bits mean what we think they mean".

`q4_k_m` is not a uniform format and that is why both decoders are exercised by
one file: llama.cpp leaves `token_embd.weight` and the attention/FFN projections
in `q4_k` and promotes `attn_v`, `ffn_down` and `output.weight` to `q6_k`. The
tied embedding is `q4_k` and is read by `embedding_quant`; the head is `q6_k`
and is read by `gemm_quant`. Both paths run on every token.

**The logits are not compared elementwise against llama.cpp, and the reason is
worth stating.** llama.cpp's `q4_K` dot product does not decode the weight and
multiply it by a float activation: it quantizes the *activation* to int8
(`block_q8_K`) and does an integer product, then scales once. That is a
different computation from ours -- we keep the activation in float32 -- and the
extra int8 step is a real error of its own. On a one-token prompt, where the
hidden state is far from the range the activation quantizer expects, llama.cpp's
own q4_k answer sits 3.53 (mean absolute) away from its f16 answer to the same
prompt, while *ours* sits 3.77 away -- and ours is what the decode loop then
uses. Measured against the f16 logits as ground truth, the two quantized results
are within 0.50 (mean) of each other over logits spanning 30.

So what is compared elementwise is the thing that has a right answer: the greedy
sequence, where both implementations agree exactly, and the top of the
distribution, where they agree in order. A bit-layout error moves a weight by a
large fraction of its own range and would break both; a different accumulation
order breaks neither.

Everything skips without the library, the checkpoint or llama.cpp. A skip is not
a pass.
"""

from __future__ import annotations

import pathlib

import pytest

from pocketllm import native

from llama_oracle import LLAMA_LIB, compile_tool, generated, logits as oracle_logits, tool_path

#: The checkpoint `llama-quantize` produced from the f16 one this tree's other
#: tests use, at `Q4_K_M`. Not generated by the test suite: quantizing is a
#: six-second CPU job and a 456 MB artifact, and a suite that built its own
#: would be comparing a file against itself.
CHECKPOINT = pathlib.Path("/mnt/data1/models/qwen3-0.6b-q4_k_m.gguf")

#: The format the f16 tests use, kept here for the one test that compares the
#: two: a quantized checkpoint should answer the *same* question as the full
#: precision one for as long as quantization does not change the argmax.
DENSE_CHECKPOINT = pathlib.Path("/mnt/data1/models/qwen3-0.6b-f16.gguf")

#: How far a `q4_k`/`q6_k` product may drift from llama.cpp's, relative to the
#: logit range. The ABI's number for a quantized product, and the same one
#: `test_op_conformance.py` uses. See the module docstring for what it buys.
QUANTIZED_RTOL = 5e-2

#: How far the two backends may drift from each other on the same packed
#: weights. Tighter than the bound above because this compares two association
#: orders of the same decode with no third party in between -- the measured
#: figure is around 2e-5 of the range.
BACKEND_RTOL = 2e-4

#: `"The capital of France is"`, as ids -- the same prompt `test_forward.py`
#: uses, for the same reason: a tokenizer regression must not read as a
#: forward-pass one.
PROMPT = [785, 6722, 315, 9625, 374]


def _needs_llama() -> str | None:
    if not LLAMA_LIB.is_file():
        return f"no llama.cpp build at {LLAMA_LIB}"
    return None


needs_engine = pytest.mark.skipif(not native.is_available(), reason="libpocketllm.so is not built")
needs_checkpoint = pytest.mark.skipif(
    not CHECKPOINT.is_file(),
    reason=f"no quantized checkpoint at {CHECKPOINT} (llama-quantize the f16 one)",
)
needs_llama = pytest.mark.skipif(_needs_llama() is not None, reason=_needs_llama() or "")

pytestmark = [needs_engine, needs_checkpoint, needs_llama]


@pytest.fixture(scope="session", autouse=True)
def oracle_tool() -> None:
    """Compile `src/tools/oracle.cpp` if it is not already built."""
    if not tool_path().is_file():
        compile_tool()


def _cuda_probe() -> str | None:
    """Why `cuda` cannot be used here, or None if it can.

    The same probe `test_forward.py` uses: open a path that does not exist, and
    read which of the two refusals comes back. It costs no checkpoint load and
    it is the ordering `pocketllm_open` documents -- device first, file second.
    """
    if not native.is_available():
        return "libpocketllm.so is not built"
    try:
        native.Engine.open(str(CHECKPOINT.with_suffix(".does-not-exist.gguf")), "cuda")
    except native.EngineUnavailable as exc:
        message = str(exc)
        return message if "cuda" in message and "not in this build" in message else None
    return "the cuda probe unexpectedly succeeded"


BACKENDS = ["cpu"]
_cuda_reason = _cuda_probe() if CHECKPOINT.is_file() else "no checkpoint"
if _cuda_reason is None:
    BACKENDS.append("cuda")


def _device_param(name: str) -> pytest.ParameterSet:
    if name in BACKENDS:
        return pytest.param(name, id=name)
    return pytest.param(name, marks=pytest.mark.skipif(True, reason=_cuda_reason or ""), id=name)


DEVICES = [_device_param(name) for name in ("cpu", "cuda")]


def _worst(a: list[float], b: list[float]) -> float:
    assert len(a) == len(b), f"logit vectors differ in length: {len(a)} vs {len(b)}"
    return max(abs(x - y) for x, y in zip(a, b))


#: The prompts the logits comparison is made on. A one-token prefix is
#: deliberately absent: with no context the hidden state is far outside the
#: range llama.cpp's int8 activation quantizer is built for, and the two
#: quantized results disagree by 12% of the logit range -- enough that they even
#: pick different argmaxes. That is a statement about the activation quantizer
#: on a degenerate input, not about the weight decoder under test.
LOGIT_PROMPTS = [[785, 6722], PROMPT]


@pytest.mark.parametrize("device", DEVICES)
@pytest.mark.parametrize("tokens", LOGIT_PROMPTS)
def test_the_logits_track_llama_cpp(device: str, tokens: list[int]) -> None:
    """The quantized logits are close to llama.cpp's on the same file, and the
    argmax is the same.

    Not an exact comparison -- see the module docstring for why llama.cpp is not
    an oracle for the *value* of a quantized logit. What survives the two
    implementations' different activation precision is the shape of the
    distribution, and the part of it with no tolerance in it is which token
    wins. Measured, the two agree to 2.5% of the logit range on the full prompt.
    """
    expected = oracle_logits(str(CHECKPOINT), tokens)
    with native.Engine.open(str(CHECKPOINT), device) as engine:
        got = engine.forward(tokens)

    spread = max(expected) - min(expected)
    worst = _worst(got, expected)
    assert worst <= QUANTIZED_RTOL * spread, (
        f"max |ours - llama| = {worst} over a spread of {spread}"
    )
    assert got.index(max(got)) == expected.index(max(expected)), "the argmax differs"


@pytest.mark.parametrize("device", DEVICES)
def test_the_greedy_sequence_matches_llama_cpp(device: str) -> None:
    """Sixteen greedy tokens, through the packed kernels on every layer.

    This is the sharpest check in the file and the one that is exact. Every step
    runs all twenty-eight layers of packed weights and a packed embedding
    gather, and the answer is a discrete choice with no tolerance: a weight read
    from the wrong bit field changes it, and this is what says so. The two
    implementations agree on every token, which a bit-layout error could not
    survive and a difference in accumulation precision could.
    """
    steps = 16
    expected = generated(str(CHECKPOINT), PROMPT, steps)

    with native.Engine.open(str(CHECKPOINT), device) as engine:
        ours = []
        token = engine.argmax(engine.forward(PROMPT))
        for step in range(steps):
            ours.append(token)
            if step + 1 < steps:
                token = engine.argmax(engine.forward([token]))

    assert ours == expected, (
        f"diverged at step "
        f"{next(i for i, (a, b) in enumerate(zip(ours, expected)) if a != b)}"
    )


@pytest.mark.parametrize("device", DEVICES)
def test_the_incremental_path_agrees_with_the_batched_one(device: str) -> None:
    """The KV cache's contract, checked under packed weights.

    `test_forward.py` makes this comparison on f16 and it is what caught the
    missing layer dimension in the cache. It is repeated here because the
    quantized path has its own scratch to get wrong -- `embedding_quant` writes
    a row per token, and a row stride computed from the wrong block width is
    invisible to a single batched prefill whose positions happen to line up.
    """
    with native.Engine.open(str(CHECKPOINT), device) as engine:
        batched = engine.forward(PROMPT)

    splits = []
    for cut in (1, 2, 3, 4):
        with native.Engine.open(str(CHECKPOINT), device) as engine:
            engine.forward(PROMPT[:cut])
            splits.append(engine.forward(PROMPT[cut:]))

    for cut, incremental in zip((1, 2, 3, 4), splits):
        worst = _worst(batched, incremental)
        assert worst == 0.0, f"splitting the prompt at {cut} changed the logits by {worst}"


def test_the_backends_agree_on_a_quantized_checkpoint() -> None:
    """The CPU and the card decode the same blocks the same way.

    The same comparison `test_forward.py` makes for f16, and here it is the one
    that matters for a format neither backend has a third party to check
    against per-op: `gemm_quant` is written twice -- `kernels.cpp` and
    `backend.cu` -- and they share only the decoder header. A card kernel that
    mis-indexed a block would pass the op-level test only if the CPU kernel did
    the same, and this compares them on 151936 logits per call with no numpy in
    between.
    """
    if "cuda" not in BACKENDS:
        pytest.skip(_cuda_reason or "cuda is not available")

    with native.Engine.open(str(CHECKPOINT), "cpu") as engine:
        host = engine.forward(PROMPT)
    with native.Engine.open(str(CHECKPOINT), "cuda") as engine:
        card = engine.forward(PROMPT)

    spread = max(host) - min(host)
    worst = _worst(host, card)
    assert worst <= BACKEND_RTOL * spread, f"max |cpu - cuda| = {worst} over a spread of {spread}"
    assert host.index(max(host)) == card.index(max(card)), "the two backends disagree on the argmax"


@pytest.mark.skipif(
    not DENSE_CHECKPOINT.is_file(), reason=f"no f16 checkpoint at {DENSE_CHECKPOINT}"
)
@pytest.mark.parametrize("device", DEVICES)
def test_the_quantized_answer_is_what_llama_cpp_gets_from_the_same_file(
    device: str,
) -> None:
    """Ours on `q4_k_m` equals llama.cpp's on `q4_k_m`, and *not* the f16 answer.

    Both halves of that are the test, and the second is the one that is easy to
    mistake for a failure. Quantizing to 4.5 bits per weight is lossy, and
    lossily enough to send this model's continuation down a different branch
    after the first token: our f16 checkpoint starts `" The capital of France is
    Paris, and the capital of Italy is Rome"`, and both ours and llama.cpp's
    q4_k_m start `" The capital of France is the capital of the"`. Asserting
    that the quantized answer stays with the f16 one would be asserting the
    quantizer did nothing.

    So this compares four sequences and requires the two q4_k_m ones to be
    equal -- which is the statement that our decode of the file is the decode
    the file's author gets -- and records that the f16 pair is a *different*
    pair, so a future change that made all four agree would fail here rather
    than pass quietly.
    """
    steps = 8

    def ours(checkpoint: pathlib.Path) -> list[int]:
        with native.Engine.open(str(checkpoint), "cpu") as engine:
            out = []
            token = engine.argmax(engine.forward(PROMPT))
            for step in range(steps):
                out.append(token)
                if step + 1 < steps:
                    token = engine.argmax(engine.forward([token]))
        return out

    quantized = ours(CHECKPOINT)
    dense = ours(DENSE_CHECKPOINT)
    their_quantized = generated(str(CHECKPOINT), PROMPT, steps)
    their_dense = generated(str(DENSE_CHECKPOINT), PROMPT, steps)

    assert quantized == their_quantized, (
        f"ours {quantized} vs llama.cpp {their_quantized} on the same q4_k_m file"
    )
    assert dense == their_dense, f"ours {dense} vs llama.cpp {their_dense} on f16"
    assert quantized != dense, (
        "the quantized and f16 sequences agree; either the quantization stopped "
        "being lossy or one of the two checkpoints is not what it claims"
    )